export const weatherCodeDescriptions = {
  "0": "clear",
  "1": "clear",
  "2": "cloudy",
  "3": "cloudy",
  "45": "cloudy",
  "48": "cloudy",
  "51": "rainy",
  "53": "rainy",
  "55": "rainy",
  "61": "rainy",
  "63": "rainy",
  "65": "rainy",
  "71": "rainy",
  "73": "rainy",
  "75": "rainy",
  "80": "rainy",
  "81": "rainy",
  "82": "rainy",
  "95": "storm",
  "96": "storm",
  "99": "storm",
};

export const weatherCodeDescriptionsPer = {
  0: "صاف",
  1: "صاف",
  2: "ابری",
  3: "ابری",
  45: "ابری",
  48: "ابری",
  51: "بارانی",
  53: "بارانی",
  55: "بارانی",
  61: "بارانی",
  63: "بارانی",
  65: "بارانی",
  71: "بارانی",
  73: "بارانی",
  75: "بارانی",
  80: "بارانی",
  81: "بارانی",
  82: "بارانی",
  95: "طوفان",
  96: "طوفان",
  99: "طوفان",
};
